backend:
  name: git-gateway
  branch: master
  repo: rutatuckute/the-non-fictional

media_folder: "images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: 6edb3445593ce1385afa

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: '{{title}}/index'
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Category Id", name: "category_id", widget: "string"}
      - {label: "Topics", name: "topic", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: true}
  # - name: "photography"
  #   label: "Photography"
  #   folder: "content/photography"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Body", name: "body", widget: "markdown"}