export const VISUAL_SCENES = [
  {
    id: "unsorted",
    layout: "scatter",
    territoriesVisible: false,
    inquiryLabelsVisible: false,
    formatIndexVisible: false,
    workTitlesVisible: false,
    connectionsVisible: false,
    timelineVisible: false,
  },
  {
    id: "formats",
    layout: "formats",
    territoriesVisible: false,
    inquiryLabelsVisible: false,
    formatIndexVisible: true,
    workTitlesVisible: true,
    connectionsVisible: false,
    timelineVisible: false,
  },
  {
    id: "inquiries",
    layout: "inquiries",
    territoriesVisible: true,
    inquiryLabelsVisible: true,
    formatIndexVisible: false,
    workTitlesVisible: false,
    connectionsVisible: false,
    timelineVisible: false,
  },
  {
    id: "network",
    layout: "network",
    territoriesVisible: false,
    inquiryLabelsVisible: false,
    formatIndexVisible: false,
    workTitlesVisible: false,
    connectionsVisible: true,
    timelineVisible: false,
  },
  {
    id: "timeline",
    layout: "timeline",
    territoriesVisible: false,
    inquiryLabelsVisible: false,
    formatIndexVisible: false,
    workTitlesVisible: false,
    connectionsVisible: false,
    timelineVisible: true,
  },
]
